#:schema node_modules/wrangler/config-schema.json
name = "dowins-xp"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./public"
dev.port = 8000

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "dowins-xp"
database_id = "8fe92680-ccb6-4f56-8d8d-75fa3154399b"
